name: Create or Label Mirror Issue
on:
  issues:
    types:
      - labeled

env:
  GH_TOKEN: ${{ secrets.DUCKDBLABS_BOT_TOKEN }}
  TITLE_PREFIX: "[duckdb-wasm/#${{ github.event.issue.number }}]"
  PUBLIC_ISSUE_TITLE: ${{ github.event.issue.title }}

jobs:
  create_or_label_issue:
    if: github.event.label.name == 'reproduced'
    runs-on: ubuntu-latest
    steps:
      - name: Get mirror issue number
        run: |
          gh issue list --repo duckdblabs/duckdb-internal --search "${TITLE_PREFIX}" --json title,number --state all --jq ".[] | select(.title | startswith(\"$TITLE_PREFIX\")).number" > mirror_issue_number.txt
          echo "MIRROR_ISSUE_NUMBER=$(cat mirror_issue_number.txt)" >> $GITHUB_ENV

      - name: Print whether mirror issue exists
        run: |
          if [ "$MIRROR_ISSUE_NUMBER" == "" ]; then
            echo "Mirror issue with title prefix '$TITLE_PREFIX' does not exist yet"
          else
            echo "Mirror issue with title prefix '$TITLE_PREFIX' exists with number $MIRROR_ISSUE_NUMBER"
          fi

      - name: Create or label issue
        run: |
          export LABEL="Wasm"
          if [ "$MIRROR_ISSUE_NUMBER" == "" ]; then
            gh issue create --repo duckdblabs/duckdb-internal --label "$LABEL" --title "$TITLE_PREFIX - $PUBLIC_ISSUE_TITLE" --body "See https://github.com/duckdb/duckdb-wasm/issues/${{ github.event.issue.number }}"
          fi

